import "tw-elements/dist/css/tw-elements.min.css";
import 'react-toastify/dist/ReactToastify.css'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Nav from './components/Nav'
import { ToastContainer } from "react-toastify"
import Script from "next/script";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <script src="https://kit.fontawesome.com/8114a7cb4e.js" crossOrigin="anonymous" />
      </head>
      <body className={inter.className}>
        {<Nav />}
        {children}
        <ToastContainer />
      </body>
    </html>
  )
}
